module.exports = {
  index: '/',
  start: '/start',
  taskList: '/task-list',
  homeOfficeDetails: '/home-office-details',
  personalDetails: '/personal-details',
  dateOfBirth: '/date-of-birth',
  contactDetails: '/your-contact-details',
  typeOfAppeal: '/type-of-appeal',
  checkAnswers: '/check-answers',
  appealSubmitted: '/appeal-submitted',
  health: '/health',
  readiness: '/readiness',
  liveness: '/liveness',
  robots: '/robots.txt',
  endSession: '/end-session',
  signIn: '/sign-in',
  register: '/register',
  createPassword: '/create-password',
  accountCreated: '/account-created',
  checkYourEmail: '/check-your-email',
  caseBuildingOverview: '/case-building/overview',
  whyAppealingDescription: '/case-building/why-appealing-description',
  reasonsForAppeal: '/case-building/reasons-for-appeal',
  caseBuildingCheckAnswers: '/case-building/check-answers',
  caseBuildingSubmitted: '/case-building/submitted'
};
