infrastructure_env  = "preprod"
additional_hostname = "ia-aip-proto-frontend.nonprod.platform.hmcts.net"
s2s_url = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
idam_url = "http://idam-api.aat.platform.hmcts.net"
idam_systemupdate_user = "ia.legalrep.a.ccd@gmail.com"
ccd_url = "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
idam_redirect_url = "https://ia-case-api-aat.service.core-compute-aat.internal/oauth2/callback"
